### ISSUE TITLE
支持生产日期时间+xx

### ISSUE THREAD

**Issue by mashuangwei** [Ahoo-Wang/CosId#100]
订单号通常是日期时间+xxx，比如20220520142030+87663233， 请教这个生产这种格式的序列号支持吗？

**Comment by Ahoo-Wang** [comment]
可以使用 
https://github.com/Ahoo-Wang/CosId/blob/main/cosid-core/src/main/java/me/ahoo/cosid/converter/SnowflakeFriendlyIdConverter.java

https://cosid.ahoo.me/guide/cosid-jackson.html#%E5%AE%89%E8%A3%85

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/blob/36eb2d45c848ccc41d1076076b7ab0b6e5fc6001/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/IdConverterDefinition.java#L84

**Comment by Ahoo-Wang** [comment]
@mashuangwei Do you have any other questions, if not, the issue will be closed.
