### ISSUE TITLE
应用宕机，对应zk节点不会被删除

### ISSUE THREAD

**Issue by mashuangwei** [Ahoo-Wang/CosId#101]
假如应用宕机或者直接被kill掉，zk对应的节点不会被删除，导致应用在zk生成的节点会生成越来越多，宕机一次多生成一次。为什么这个节点不做成临时节点？这样宕机节点也会被删除。

![image](https://user-images.githubusercontent.com/7100779/169468346-06c1813b-52ce-4856-826d-2bb6608cb8fc.png)

**Comment by Ahoo-Wang** [comment]
[SnowflakeId之时钟回拨问题](https://cosid.ahoo.me/guide/#snowflakeid%E4%B9%8B%E6%97%B6%E9%92%9F%E5%9B%9E%E6%8B%A8%E9%97%AE%E9%A2%98)。

因为是要存储 `lastStamp`，解决启动时回拨的问题。另外因为`MachineIdGuarder`机制，不用担心因为非优雅关闭导致的机器号未被回收。
![image](https://user-images.githubusercontent.com/4384159/169470415-4ebd4d86-c951-4c0a-80c5-a9c1af3e73fa.png)
![image](https://user-images.githubusercontent.com/4384159/169470388-f8ee43ee-862d-4242-9212-6b27a8c52b59.png)

**Comment by Ahoo-Wang** [comment]
相关的测试规范的约定在这里：
https://github.com/Ahoo-Wang/CosId/blob/36eb2d45c848ccc41d1076076b7ab0b6e5fc6001/cosid-test/src/main/java/me/ahoo/cosid/test/snowflake/machine/distributor/DistributeSafeGuard.java#L73

**Comment by Ahoo-Wang** [comment]
Do you have any other questions, if not, the issue will be closed.
