### ISSUE TITLE
Help specific documents

### ISSUE THREAD

**Issue by AprilViolet** [Ahoo-Wang/CosId#11]
Hello, in combination with whether there are specific documents for springboot, I can see that there are some configurations in readme, but there is no specific description for many springboot configurations. Can you provide a specific configuration description? Furthermore, the description of different packages in Maven warehouse. thank you
> And are there best practices.
> Moreover, the [cosid-rest-api](https://github.com/Ahoo-Wang/CosId/tree/main/cosid-rest-api) failed

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/tree/main/cosid-example

**Comment by AprilViolet** [comment]
Thanks,If you can explain some configuration parameters, it is better.

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/tree/main/document

https://ahoo-wang.github.io/CosId/config/

**Comment by AprilViolet** [comment]
@Ahoo-Wang Thanks, good document is also a major progress of the project.If possible, I will also contribute in the future.

**Comment by Ahoo-Wang** [comment]
The document was just written in these two days. It can't be comprehensive. I look forward to your contribution.
