### ISSUE TITLE
在使用k8s的HPA做弹性伸缩的时候，可能存在的号段被浪费的问题

### ISSUE THREAD

**Issue by telechow** [Ahoo-Wang/CosId#115]
**Is your feature request related to a problem? Please describe.**
第一点，我所在的小庙，为了运维方便，使用k8s来维护生产环境的项目，且使用了HPA做弹性伸缩。
有些项目，存在这样的情况：没有人用的时候，一天都没有几个请求，一旦有人使用到业务高峰的时候，可能会有3k多的并发。庙里配备的运维人员又少，所以类似这样的项目，我们暂时采用k8s的HPA功能做弹性伸缩，事实上也有着很不错的表现。
然后cosid，号段链模式，将会有prefetchWorker线程，预取号段，被预取的号段，将会维护在服务的内存中，不会持久化（如果没有理解错的话）。我看了您的文档，并不怀疑cosid的性能。
但是可能在业务高峰的时候，k8s弹性伸缩，java服务的deployment多出很多个pod，然后这多个实例都预取了号段，且并发越大安全距离会越大，预取号段会越多，正常使用扛过高峰之后，k8s又会弹性伸缩移除掉很多pod。这些被移除的pod预取的号段，可能还没有使用，然后pod就没了，号段就浪费了，id就浪费了。实际存储在库里的id就可能会有较大的不连续。
但是其实我们庙里的业务量根本远远不可能将Long型的id用完，所以这里的号段浪费其实是可以容忍的。

第二点，我所在的小庙有些业务要使用到bitset，之前好多项目使用的是雪花算法变种作为分布式id的解决方案。但是雪花算法对bitset的使用非常不友好，所以我考虑改用号段算法去实现分布式id，然后就查到了cosid这个项目。
在号段被浪费的情况下，bitset的长度可能会受到影响，消耗更多内存。即使我对bitset进行分片，也有可能因为号段中id的浪费，导致分片的bitset中存在大量0，和少量1的情况，造成内存的浪费。请问有没有什么优化的手段？

**Describe the solution you'd like**
我阅读了cosid的文档，认为可以将号段步长“step”配置的小一点，安全距离"safe-distence"配置小一点，可以尽可能的减少号段和id的浪费。

**Describe alternatives you've considered**
可不可以有一种新的预取号段的方式。现有cosid的prefetchWorker会自适应的改变安全距离“safe-distence”。
prefetchWorker自适应改变预取周期“prefetch-period”。并发越高，预取周期越短，然后安全距离固定。来实现？

或者将使用号段和使用完毕号段的信息和时间持久化。每隔一段时间将那些比较古老的，没有使用过号段回收。但是这样会打破趋势递增的规则。

**Additional context**
无

**Comment by telechow** [comment]
另外，我看文档有很多不全。你们需要人帮忙编写文档吗？我可以抽业余时间提供帮助。

**Comment by Ahoo-Wang** [comment]
> **Describe the solution you'd like** 我阅读了cosid的文档，认为可以将号段步长“step”配置的小一点，安全距离"safe-distence"配置小一点，可以尽可能的减少号段和id的浪费。

@telechow  是的，你理解的是完全正确的。

> 可不可以有一种新的预取号段的方式。现有cosid的prefetchWorker会自适应的改变安全距离“safe-distence”。
prefetchWorker自适应改变预取周期“prefetch-period”。并发越高，预取周期越短，然后安全距离固定。来实现？

从预取调度效率、以及收益上来说，由消费方主动告知`hungry`(饥饿)，使 `PrefetchWorker` 加快预取是不需要定时器的，并且基于消费方直接需求作为调度依据成本是最低的。
另外安全距离固定意味着需要更多的网络IO来请求号段。

**Comment by Ahoo-Wang** [comment]
> 另外，我看文档有很多不全。你们需要人帮忙编写文档吗？我可以抽业余时间提供帮助。

非常期待你的贡献啊。

文档源码地址在这里：https://github.com/Ahoo-Wang/CosId/tree/main/document

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/171600338-01f44a39-dca3-452d-bf6f-d62e1cb26dd3.png)

另外我们从这张图上可以看到，号段链模式 `step=1` 跟 `step=1000` 性能上并没有差距。

**Comment by bwzhang2011** [comment]
@Ahoo-Wang  cosid的性能已经很优秀了、但没有解决序列号如果是用在IM场景、是要承诺严格递增的——微信自身提供了解决方案（太复杂）、然后市面上也有https://github.com/netease-im/camellia/blob/master/docs/id-gen/id-gen.md 想了解一下 如何基于cosid实现严格的消息递增

**Comment by bwzhang2011** [comment]
@Ahoo-Wang 有时间能否view一下、即cosid能否有支持严格递增的解决方案（像微信序列号：http://www.52im.net/thread-1998-1-1.html ）该方案满足高可用的。原先项目是考虑基于cosid-jdbc、但由于其不支持严格递增后面只能改成最早的DB自增的消息序列号的解决方案。
