### ISSUE TITLE
SecondSnowflakeId 构造函数 epoch 默认值错误

### ISSUE THREAD

**Issue by WangXiaoJin** [Ahoo-Wang/CosId#129]
## Bug Report

Before report a bug, make sure you have:

- [x] Searched open and closed [GitHub issues](https://github.com/Ahoo-Wang/CosId/issues).
- [x] Read documentation: [CosId Doc](https://cosid.ahoo.me/).

### Which version of CosId did you use?
> 1.10.0

### Reason analyze (If you can)

```java
    public SecondSnowflakeId(long machineId) {
        this(CosId.COSID_EPOCH_SECOND, DEFAULT_TIMESTAMP_BIT, DEFAULT_MACHINE_BIT, DEFAULT_SEQUENCE_BIT, machineId);
    }

    public SecondSnowflakeId(int machineBit, long machineId) {
        super(CosId.COSID_EPOCH, DEFAULT_TIMESTAMP_BIT, machineBit, DEFAULT_SEQUENCE_BIT, machineId);
    }
```

这两个构造函数的`epoch`值不同，第二个应该使用`CosId.COSID_EPOCH_SECOND`

**Comment by Ahoo-Wang** [comment]
非常感谢你的反馈，你可以提交PR修复该问题吗
