### ISSUE TITLE
The Doc  is wrong 

### ISSUE THREAD

**Issue by geutopia** [Ahoo-Wang/CosId#135]
The  https://cosid.ahoo.me/config/snowflake.html#iddefinition    Is wrong  

The right example :

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
    guarder:
      enabled: true
    machine-bit: 8
  snowflake:
    enabled: true
    zone-id: Asia/Shanghai
    epoch: 1660000000000
    provider:
      order_item:
        timestamp-bit: 40
        sequence-bit: 8

**Comment by Ahoo-Wang** [comment]
Thanks a lot for your feedback, can you fix the issue and submit a PR. This is the document url: 
https://github.com/Ahoo-Wang/CosId/blob/main/document/docs/config/snowflake.md
