### ISSUE TITLE
It's better to return consistent sub-type of Collection in IntervalTimeline.sharding method

### ISSUE THREAD

**Issue by sandynz** [Ahoo-Wang/CosId#14]
**Is your feature request related to a problem? Please describe.**

CosId was added in Apache ShardingSphere recently, when I'm running `shardingsphere-sharding-core` module's unit test in IDEA, it has some failed cases of `CosIdIntervalShardingAlgorithmTest` which are related with `IntervalTimeline.sharding`. Failed result:
<img width="1324" alt="图片" src="https://user-images.githubusercontent.com/42492540/148635411-d9117480-79c0-4448-9aa4-b6fd941855bf.png">

Related code:
```
        @Test
        public void assertDoSharding() {
            RangeShardingValue shardingValue = new RangeShardingValue<>(LOGIC_NAME, COLUMN_NAME, rangeValue);
            Collection<String> actual = shardingAlgorithm.doSharding(ALL_NODES, shardingValue);
            assertThat(actual, is(expected));
        }
```

In fact, `actual` and `expected` has the same elements, but they're different `Collection`'s sub-type, so they're not equals. Debug screenshot:
<img width="1069" alt="WX20220108-124508@2x" src="https://user-images.githubusercontent.com/42492540/148635476-0860d91c-64b0-439a-98cf-9506932ca3ae.png">

`actual` is instance of `Collections$SingletonSet`, but `expected` is instance of `ExactCollection`.

**Describe the solution you'd like**

In `IntervalTimeline.java`
```
    @Override
    public Collection<String> sharding(Range<LocalDateTime> shardingValue) {
//...
        if (lowerOffset == upperOffset) {
            return Collections.singleton(lastInterval.getNode());
        }
//...
        ExactCollection<String> nodes = new ExactCollection<>(nodeSize);
//...
        return nodes;
    }
```

`Collections.singleton(lastInterval.getNode())` could be replaced to return `ExactCollection` or , just like other return statements.

**Describe alternatives you've considered**

It's possible to fix it by changing`expected` in `CosIdIntervalShardingAlgorithmTest.rangeArgsProvider`, but it's a little strange, users should not concern about the implementation of `IntervalTimeline.sharding`.

**Additional context**

**Comment by Ahoo-Wang** [comment]
> Collections.singleton(lastInterval.getNode()) could be replaced to return ExactCollection or , just like other return statements.

Agreed, I'll modify the return value later.

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/commit/c439165436bb8e21766a0acc640bd7827f437ea7

Changed in `v1.7.6`.

![image](https://user-images.githubusercontent.com/4384159/148637775-da814ca1-b240-45be-833e-bd5c97a525d0.png)

But it will take some time to sync to the central repository.

**Comment by sandynz** [comment]
That's OK, Thank you~

**Comment by sandynz** [comment]
Could you help to update cosid version in Apache ShardingSphere when `v1.7.6` is synchronized to central repository?

**Comment by Ahoo-Wang** [comment]
> 

OK

**Comment by Ahoo-Wang** [comment]
> Could you help to update cosid version in Apache ShardingSphere when `v1.7.6` is synchronized to central repository?

OK
