### ISSUE TITLE
PrefetchWorkerExecutorService的关闭钩子（ShutdownHook）可能需要使用者关闭

### ISSUE THREAD

**Issue by cubita-io** [Ahoo-Wang/CosId#16]
![image](https://user-images.githubusercontent.com/59306969/149432463-7e02c387-3675-442f-a229-dd9fb341e87a.png)

如果Distributor类型为JDBC或者其他，这个自动关闭钩子，如果运行在数据库关闭之后，那边会引起访问数据库，建议让使用者来决定是否由cosid关闭；增加一个是否自动关闭的属性或者构造函数设置，使用者可以设置

**Comment by Ahoo-Wang** [comment]
agree.

**Comment by Ahoo-Wang** [comment]
nice! merged.

**Comment by Ahoo-Wang** [comment]
@cubita-io  还有 spring-boot-starter 自定义配置部分的内容需要完成。
https://github.com/Ahoo-Wang/CosId/blob/831eeb4cbda6ef7da0ca66a67b6fa2021e1ad93b/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdSegmentAutoConfiguration.java#L64

**Comment by cubita-io** [comment]
https://github.com/Ahoo-Wang/CosId/pull/18
https://github.com/Ahoo-Wang/CosId/pull/19

**Comment by Ahoo-Wang** [comment]
你可以把俩个PR 合并到一起吗

**Comment by cubita-io** [comment]
https://github.com/Ahoo-Wang/CosId/pull/18
https://github.com/Ahoo-Wang/CosId/pull/19
https://github.com/Ahoo-Wang/CosId/pull/20
麻烦把这两个都关闭了吧 我重新提交

**Comment by Ahoo-Wang** [comment]
thx , #20 merged.
