### ISSUE TITLE
cosid-mybatis插件会导致正常的sql语句无法执行

### ISSUE THREAD

**Issue by JkChenz** [Ahoo-Wang/CosId#168]
![image](https://user-images.githubusercontent.com/35361484/198220602-dc86de7a-1cd7-4418-b07e-747b3987a129.png)
![image](https://user-images.githubusercontent.com/35361484/198220721-c73e1e0f-ebad-4fac-b39e-393e6407a862.png)

**Comment by Ahoo-Wang** [comment]
Can you provide an example URL?

**Comment by JkChenz** [comment]
[iddemo.zip](https://github.com/Ahoo-Wang/CosId/files/9876957/iddemo.zip)
I think this may let you know

**Comment by Ahoo-Wang** [comment]
I've found the problem, thank you very much for your feedback.

**Comment by Ahoo-Wang** [comment]
I will release a new version (`v1.14.9`) to fix the problem after waiting for the main branch to pass the CI check.

**Comment by JkChenz** [comment]
> I will release a new version (`v1.14.9`) to fix the problem after waiting for the main branch to pass the CI check.

ok thanks

**Comment by Ahoo-Wang** [comment]
It is estimated that it will take at least 1 day for the package to be synchronized to the Maven central repository. 
You can use the command `gradle publishToMavenLocal` to install it directly to your local repository.
