### ISSUE TITLE
是否可以支持Springboot3

### ISSUE THREAD

**Issue by aozeyu** [Ahoo-Wang/CosId#187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ahoo-Wang** [comment]
I just created https://github.com/Ahoo-Wang/CosId/tree/spring-boot-3 for checking compatibility issues.

But we are still facing some other issues:

- The stable version of spring boot 3 has not been released, let alone popularized. (This may solve the problem that Java 17 can't be popularized.)
- Spring boot 3 requires Java 17, is this too aggressive for downstream consumers of CosId.

But this does not prevent us from opening another branch to be compatible with spring-boot-3

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/releases/tag/v2.0.0-SNAPSHOT

**Comment by aozeyu** [comment]
好的谢谢你的回复,那Springboot3 稳定后是会同步支持吗。

**Comment by Ahoo-Wang** [comment]
> 好的谢谢你的回复,那Springboot3 稳定后是会同步支持吗。

@aozeyu 

目前已经支持 Spring-Boot-3 RC1 了，https://github.com/Ahoo-Wang/CosId/releases/tag/v2.0.0-RC1

https://search.maven.org/artifact/me.ahoo.cosid/cosid-core/2.0.0-RC1/jar

https://github.com/Ahoo-Wang/CosId/packages/1152391

受限于 Spring-Boot-3 破坏性变更以及 Java 17 的要求，并考虑到 CosId 下游使用者兼容性问题，之后会同步维护两个分支版本即:
- main 分支：https://github.com/Ahoo-Wang/CosId ，保持 Java 8 基线
- spring-boot-3 分支：https://github.com/Ahoo-Wang/CosId/tree/spring-boot-3 ，同步兼容 Spring-Boot-3

不过这增加了维护成本，非常欢迎参与到 *CosId* 贡献者中来。

**Comment by aozeyu** [comment]
@Ahoo-Wang 好的感谢你的回复，我目前正在研究此项目,努力能成为贡献者😂.

**Comment by aozeyu** [comment]
@Ahoo-Wang 我有一个discussions如果大佬有空的话可以帮我看看嘛

**Comment by Ryoui** [comment]
报'Spring Boot [2.4.13] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [2.6.x, 2.7.x]。cosid1.16.8，所以必须把spring boot 升级到2.6.x+以上才能用吗？有没有哪个cosid版本支持2.4.x的？
