### ISSUE TITLE
是不是叫SegmentIdGenerator更好一些？

### ISSUE THREAD

**Issue by Matrix0xCC** [Ahoo-Wang/CosId#3]
https://github.com/Ahoo-Wang/CosId/blob/4b1cffa5c3766ce678f525568f0ccb7d5458b494/cosid-core/src/main/java/me/ahoo/cosid/segment/SegmentId.java#L21

**Comment by Ahoo-Wang** [comment]
`SegmentId` 是跟 `SnowflakeId` 命名对应的。
