### ISSUE TITLE
文档麻烦写清楚点

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#308]
怎么用的，怎么配置的麻烦写清楚点，，看了文档配置 还报错，感觉好结合好几次自己摸索才知道怎么配置

**Comment by Ahoo-Wang** [comment]
This Issue does not meet the Issue specification.

**Comment by clay-f** [comment]
文档确实渣渣，是详细描述了实现过程，速度有多块，但在使用者看起来就想知道怎么使用，怎么简单配置，最后越配置越多，使用教程一点也不清楚。

The documentation is really sloppy, it describes the implementation process in detail, and the speed is very fast, but users seem to want to know how to use it and how to configure it easily. In the end, the more configurations, the more configurations, the usage tutorial is not clear at all

**Comment by Ahoo-Wang** [comment]
@knight-xiaolu2023 @clay-f 

看一下新的官方文档是否友好一些了：

快速上手：https://cosid.ahoo.me/guide/getting-started.html
特定场景下的ID配置：https://cosid.ahoo.me/guide/specific-id.html
