### ISSUE TITLE
machine 是配置在cosid下面 还是snowflake

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#311]
看文档是2个都可以，看代码是在cosid下面，有点乱

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/blob/ffa70b0041ed4274ffc276952ae9210e0ea7db3d/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/snowflake/SnowflakeIdBeanRegistrar.java#L103

machine 是全局默认的，如果自定义的ID定义了 machineId 则使用自定义的，否则使用全局默认的。

**Comment by Ahoo-Wang** [comment]
欢迎一起完善文档，非常期待你的PR。
