### ISSUE TITLE
machine.MachineProperties' that could not be found.

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#312]
![image](https://user-images.githubusercontent.com/131353676/233565576-517adf33-8001-420e-afe9-db3ffadc2948.png)

![image](https://user-images.githubusercontent.com/131353676/233565539-223a58fb-ee84-4601-9272-7eea0f955ccd.png)

![image](https://user-images.githubusercontent.com/131353676/233565635-123daf47-b036-43a1-abea-638771914c2d.png)
麻烦帮忙看看是什么原因、、

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/blob/main/examples/cosid-example-redis/src/main/resources/application.yaml


![image](https://user-images.githubusercontent.com/4384159/233568462-0d519212-71fe-4982-9f8a-819c869a29b2.png)

**Comment by knight-xiaolu2023** [comment]
改了还是不行啊

**Comment by Ahoo-Wang** [comment]
把完整 yaml 文件发给我。

**Comment by knight-xiaolu2023** [comment]
稍等
server:
    port: 8085
    tomcat:
      uri-encoding: UTF-8
      max-connections: 8192
spring:
  application:
    name: websocket
    datasource:
      #替换mysql数据库连接、用户名、密码
      url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 10
      maxActive: 100
      maxWait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: false
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  redis:
    #redis-config
    timeout: 60000
    host: 127.0.0.1
    port: 6379
    password: 52224
    lettuce:
      pool:
        #unit:second
        maxAttempts: 5
        maxActive: 8
        maxIdle: 8
        maxWait: -1
        minIdle: 1

cosid:
  namespace: ${spring.application.name}
  machine:
    stable: false
    enable: true
    distributor:
      type: redis
    guarder:
      enable: true
  snowflake:
    enabled: true
    epoch: 1288834974657
    share:
      clock-sync: true
  enabled: true

**Comment by knight-xiaolu2023** [comment]
server:
    port: 8085
    tomcat:
      uri-encoding: UTF-8
      max-connections: 8192
spring:
  application:
    name: websocket
    datasource:
      #替换mysql数据库连接、用户名、密码
      url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 10
      maxActive: 100
      maxWait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: false
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  redis:
    #redis-config
    timeout: 60000
    host: 127.0.0.1
    port: 6379
    password: 52224
    lettuce:
      pool:
        #unit:second
        maxAttempts: 5
        maxActive: 8
        maxIdle: 8
        maxWait: -1
        minIdle: 1

cosid:
  namespace: ${spring.application.name}
  machine:
    stable: false
    enable: true
    distributor:
      type: redis
    guarder:
      enable: true
  snowflake:
    enabled: true
    epoch: 1288834974657
    share:
      clock-sync: true
  enabled: true

**Comment by knight-xiaolu2023** [comment]
`server:
    port: 8085
    tomcat:
      uri-encoding: UTF-8
      max-connections: 8192
spring:
  application:
    name: websocket
    datasource:
      #替换mysql数据库连接、用户名、密码
      url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 10
      maxActive: 100
      maxWait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: false
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  redis:
    #redis-config
    timeout: 60000
    host: 127.0.0.1
    port: 6379
    password: 52224
    lettuce:
      pool:
        #unit:second
        maxAttempts: 5
        maxActive: 8
        maxIdle: 8
        maxWait: -1
        minIdle: 1

cosid:
  namespace: ${spring.application.name}
  machine:
    stable: false
    enable: true
    distributor:
      type: redis
    guarder:
      enable: true
  snowflake:
    enabled: true
    epoch: 1288834974657
    share:
      clock-sync: true
  enabled: true`

**Comment by knight-xiaolu2023** [comment]
![image](https://user-images.githubusercontent.com/131353676/233570990-80c6fea5-e75b-47aa-a66c-cb3173f18192.png)
![image](https://user-images.githubusercontent.com/131353676/233571020-871ba207-436c-4c54-9c79-674d3277be44.png)
文字发出来没缩进。。只能截图

**Comment by knight-xiaolu2023** [comment]
我换了个旧版的就好了，这个机器码分配必须要用到springcloud吗？我这边是单体服务，采用的是nginx代理，没有springcloud

**Comment by knight-xiaolu2023** [comment]
可以了，从1.16换到了1.11版
