### ISSUE TITLE
问下这个machineId会回收吗？

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#314]
一般多久会回收

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/233590385-3e243384-dae4-4d0c-b717-d538a46f1a1d.png)

**Comment by knight-xiaolu2023** [comment]
![image](https://user-images.githubusercontent.com/131353676/233592191-131b0b9e-cf6e-4b4c-bb51-dea9c13331bf.png)
我是这样配置的，这个safe_guard_duration默认是多久啊

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/blob/e56983c620a89598959c190b15f280c710a4e2a0/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/MachineProperties.java#L261

**Comment by knight-xiaolu2023** [comment]
怎么获取这个machineId
