### ISSUE TITLE
问下怎么获取machineId

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#315]
根据provider好像获取不到

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/blob/e56983c620a89598959c190b15f280c710a4e2a0/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMachineAutoConfiguration.java#L77

直接看源码，你这类问题不再回复了。

**Comment by knight-xiaolu2023** [comment]
好
