### ISSUE TITLE
IdSegmentDistributor是否可以对外扩展出一个listener，方便使用者自己扩展nextMaxId的存储？

### ISSUE THREAD

**Issue by long172066912** [Ahoo-Wang/CosId#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by long172066912** [comment]
目前我想实现nextMaxId的多级存储，因此想在RedisLoad后做一些操作，防止redis数据丢失

**Comment by Ahoo-Wang** [comment]
1. `IdSegmentDistributor` 是由 `IdSegmentDistributorFactory` 创建的。
2. 所以你可以实现自己的 `IdSegmentDistributorFactory` 来生成所需场景的 `IdSegmentDistributor` 。
3. 将 自己实现的 `IdSegmentDistributorFactory` 注入容器即可。

**Comment by long172066912** [comment]
也是一种思路！
我按照这个自己实现一个
