### ISSUE TITLE
雪花算法的41bit计算公式少了  /24 。  41-bittimestamp=(1L<<41)/(1000/3600/24/365)

### ISSUE THREAD

**Issue by ji602089383** [Ahoo-Wang/CosId#325]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ahoo-Wang** [comment]
哪里少了？

**Comment by ji602089383** [comment]
发起了，你看下

**Comment by Ahoo-Wang** [comment]
还有下面俩个文档也存在该问题。

https://github.com/Ahoo-Wang/CosId/blob/7c15de3cc515f0b6269dd71d259c4e74ed834e1c/README.zh-CN.md?plain=1#L136

https://github.com/Ahoo-Wang/CosId/blob/main/document/docs/guide/README.md
