### ISSUE TITLE
请问是否可以把main分支最近的提交合并到springboot3，并发布新版本到maven仓库呢

### ISSUE THREAD

**Issue by AprilViolet** [Ahoo-Wang/CosId#337]
请问是否可以把main分支最近的提交合并到springboot3，并发布新版本到maven仓库呢，我看springboot3分支最近的版本还是2022年的

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/releases/tag/v2.0.6
