### ISSUE TITLE
分布式情况下，雪花Redis方式machineId分配问题

### ISSUE THREAD

**Issue by long172066912** [Ahoo-Wang/CosId#34]
节点一直重启的情况下，machineId是不是会超出上限？

**Comment by Ahoo-Wang** [comment]
重启时 `machineId` 是会回收的。(暴力关闭进程可能导致`machineId` 无法回收)

![RedisMachineIdDistributor](https://raw.githubusercontent.com/Ahoo-Wang/CosId/main/document/docs/.vuepress/public/assets/design/RedisMachineIdDistributor.png)

https://github.com/Ahoo-Wang/CosId/blob/ae89be97ef82ff51ba4ad8b4f848e39e15042f52/cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/snowflake/CosIdLifecycleMachineIdDistributor.java#L50

**Comment by long172066912** [comment]
我知道会收回，但是我看adder还是会一直往上涨

**Comment by Ahoo-Wang** [comment]
如果回收站没有可用的 `machineId` ，`adder` 是会上涨的。
一般遵循以下公式：
adder - 回收站 `machineId` 数量 ≈ 当前运行的节点数

**Comment by long172066912** [comment]
了解，之前的问题是因为运维K8S直接暴力干掉POD，没有通知服务导致！

**Comment by long172066912** [comment]
回收revert是否用其他结构更简单，比如set，可以随机弹出一个？
目前lua里
local machineData = redis.call('hgetall', instanceRevertKey);
是调用hgetall实现

**Comment by Ahoo-Wang** [comment]
> 回收revert是否用其他结构更简单，比如set，可以随机弹出一个？ 目前lua里 local machineData = redis.call('hgetall', instanceRevertKey); 是调用hgetall实现

`revert` 还需要维护 上一次使用的节点的时间戳。防止启动时时钟回拨。
