### ISSUE TITLE
在号段模式下能否增加获取指定位数的ID。

### ISSUE THREAD

**Issue by zhong2312** [Ahoo-Wang/CosId#340]
比如Long最大是19位，那么我可以获取15位的Long。剩余的4位我可以拼接其它数字。
nextId(15) 返回 1234567891234560000。
nextId(13) 返回 1234567891234000000。

这样就可以实现订单ID+会员ID后X位分库分表
订单ID=nextId(14) 返回 1234567891234500000。
订单ID+会员ID= 1234567891234588888。
那么订单ID可以有几十万亿个。而会员ID分表最多也支持十万级别的表。

**Comment by Ahoo-Wang** [comment]
你可以自定义：
https://github.com/Ahoo-Wang/CosId/blob/da91e0c36f3d7b6db94602b2ce4892eecc2a3edd/cosid-core/src/main/java/me/ahoo/cosid/IdConverter.java#L25
