### ISSUE TITLE
这是什么原因

### ISSUE THREAD

**Issue by knight-xiaolu2023** [Ahoo-Wang/CosId#342]
![image](https://github.com/Ahoo-Wang/CosId/assets/131353676/17498c80-d3e7-4e0c-80bf-71421bd6317c)

**Comment by Ahoo-Wang** [comment]
![image](https://github.com/Ahoo-Wang/CosId/assets/4384159/61207f8c-793f-4593-85a9-c9188a7162fd)

机器号守卫时发现当前使用的机器号已被回收或被其他实例占用。故障排查方法：
1. 机器号分发器：Redis
2. 检查 `cosid:{cosid}:itc_idx` key 丢失原因
   2.1 key 整体丢失，Redis 故障？
   2.2 丢失的机器号[11] 已经存在 `cosid:{cosid}:revert` ， 主动回收？
   2.3 ...
