### ISSUE TITLE
为什么example中的例子跑不起来呢?

### ISSUE THREAD

**Issue by 123Mrxiao** [Ahoo-Wang/CosId#35]
![image](https://user-images.githubusercontent.com/50818397/158323280-4e5f6db1-618d-4753-addb-7503c4cf79f4.png)

**Comment by Ahoo-Wang** [comment]
运行的是 [cosid-example](https://github.com/Ahoo-Wang/CosId/tree/main/cosid-example) 吗？

**Comment by 123Mrxiao** [comment]
对的,但我迁移出去使用Maven进行构建

**Comment by Ahoo-Wang** [comment]
pom 依赖发出来看一下。

**Comment by 123Mrxiao** [comment]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.3</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-spring-boot-starter</artifactId>
            <version>${cosid.version}</version>
        </dependency>

        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-core</artifactId>
            <version>1.8.6</version>
        </dependency>

        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-jackson</artifactId>
            <version>1.8.6</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.7</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-shardingsphere</artifactId>
            <version>1.8.6</version>
        </dependency>
    </dependencies>

**Comment by 123Mrxiao** [comment]
是否缺少依赖了呢

**Comment by Ahoo-Wang** [comment]
> 是否缺少依赖了呢

是的，缺少存储后端，目前有三类存储后端：
- `cosid-jdbc`
- `cosid-spring-redis`

**Comment by 123Mrxiao** [comment]
好的,我先引入

**Comment by Ahoo-Wang** [comment]
https://cosid.ahoo.me/guide/cosid-jdbc.html

**Comment by 123Mrxiao** [comment]
我已经按照你的说法, 引入了相应的依赖但还是有些问题
![image](https://user-images.githubusercontent.com/50818397/158350363-799ed8e9-40c8-44e3-97e6-a01638de5d6f.png)

**Comment by 123Mrxiao** [comment]
我按照你的说法引入了相关的依赖, 但还是出现了一些问题
![image](https://user-images.githubusercontent.com/50818397/158350735-e3a97af1-f264-463b-8ee0-9808636a32b5.png)

**Comment by Ahoo-Wang** [comment]
异常描述很清楚啊，`EntityRepository`  没有注入啊。

**Comment by 123Mrxiao** [comment]
好的， 我采用SnowflakeId方案成功运行起来了

**Comment by Ahoo-Wang** [comment]
> 好的， 我采用SnowflakeId方案成功运行起来了

如果没有其他问题的话，请关闭该Issue吧。

**Comment by Ahoo-Wang** [comment]
#33
