### ISSUE TITLE
Whether the jdk1.8 is supported？

### ISSUE THREAD

**Issue by l84550348** [Ahoo-Wang/CosId#421]
我本地是"JDK8" 的环境，在引用 cosid 时报 “类文件具有错误的版本 61.0, 应为 52.0” 错误，请问有没有那个版本是支持"JDK8"的

**Comment by Ahoo-Wang** [comment]
请使用 ` v1.*` 版本。目前主维护版本已经切换到 `v2.*` (main 分支)

**Comment by l84550348** [comment]
好的，谢谢！
