### ISSUE TITLE
Using deprecated '-debug' fallback for parameter name resolution

### ISSUE THREAD

**Issue by hhtower** [Ahoo-Wang/CosId#481]
## Bug Report
Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: me.ahoo.cosid.spring.boot.starter.actuate.CosIdEndpoint

Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: me.ahoo.cosid.spring.boot.starter.actuate.CosIdGeneratorEndpoint

Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: me.ahoo.cosid.spring.boot.starter.actuate.CosIdStringGeneratorEndpoint

from sprint boot 3.1.4

**Comment by Ahoo-Wang** [comment]
The issue does not meet the issue specifications, please fill in the issue again
