### ISSUE TITLE
spring-boot-starter 命名规范问题

### ISSUE THREAD

**Issue by fxbin** [Ahoo-Wang/CosId#5]
* 官方命名空间（springboot 官方项目）
前缀：spring-boot-starter-
模式：spring-boot-starter-{模块名}
举例：spring-boot-starter-web、spring-boot-starter-jdbc
* 自定义命名空间（非springboot 官方）
后缀：-spring-boot-starter
模式：{模块}-spring-boot-starter
举例：mybatis-spring-boot-starter

**Comment by Ahoo-Wang** [comment]
感谢你的反馈。预计在下一个版本进行修正。

**Comment by fxbin** [comment]
已提交PR~

**Comment by Ahoo-Wang** [comment]
效率真高，已合并。晚写时候我会发布新版到中央仓库。
