### ISSUE TITLE
JDK8 不兼容，求兼容

### ISSUE THREAD

**Issue by luoren18** [Ahoo-Wang/CosId#541]
尝试了从 1.14.3-2.6.6 版本，
高版本在编译期会报错，低版本在服务启动时报错
<img width="1370" alt="Snipaste_2024-03-08_17-04-52" src="https://github.com/Ahoo-Wang/CosId/assets/19346807/6e52e551-90a0-4b0b-b665-c632ac5cbdb3">
<img width="1420" alt="Snipaste_2024-03-08_17-16-54" src="https://github.com/Ahoo-Wang/CosId/assets/19346807/600d91cc-775f-42b3-8b50-25e6393dc01f">
本机Mac-m1 平台  zulu-8.jdk 开发环境

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/issues/421
