### ISSUE TITLE
雪花时间位压缩

### ISSUE THREAD

**Issue by jdxia** [Ahoo-Wang/CosId#570]
雪花算法, 时间戳可以减去比如2020年1月1号,然后时间最大支持30年, 并且时间是秒不是毫秒, 能大概节省一些空间出来.
请问这个支持吗?

一般我这订单号是雪花+用户id后3位, 然后分库分表, 同一个用户会分到同一个表里面, 并且希望订单id是long类型

**Comment by Ahoo-Wang** [comment]
https://cosid.ahoo.me/reference/config/snowflake.html

https://cosid.ahoo.me/guide/specific-id.html#snowflake-friendly-second
