### ISSUE TITLE
容错应该怎么实现呢？

### ISSUE THREAD

**Issue by laobinggan** [Ahoo-Wang/CosId#589]
例如我使用了redis当作分发器，假如我redis长时间崩溃，怎么来做一个可以返回id的兜底的处理？ 尤其是本地 SDK方式使用时。

**Comment by Ahoo-Wang** [comment]
你所说的容错性，对应的是指标对比图里边的自治性：

细节请阅读以下文档：

https://github.com/Ahoo-Wang/CosId/blob/main/README.zh-CN.md#%E5%88%86%E5%B8%83%E5%BC%8Fid%E6%96%B9%E6%A1%88%E7%9A%84%E6%A0%B8%E5%BF%83%E6%8C%87%E6%A0%87

![image](https://github.com/Ahoo-Wang/CosId/assets/4384159/86e1b71d-fe55-4167-8136-1886e69a082b)

---

1. 号段算法：使用更大容量的号段来降低因号段分发器临时停止服务产生的影响。
2. 雪花算法：只在服务实例启动时向机器号分发器请求分发机器号，之后便无依赖。

**Comment by Ahoo-Wang** [comment]
提升后端分发器的可用性是最优解，方案也最成熟。
