### ISSUE TITLE
如何集成到hibernate使用？

### ISSUE THREAD

**Issue by meimosor** [Ahoo-Wang/CosId#600]
我再hibernate自定义了一个ID生成器，如何在替换这里的逻辑使CosId的雪花ID生成器生效？
```
public class YuIdGenerator implements IdentifierGenerator {

    static SnowFlake snowFlake;

    static {
        snowFlake = new SnowFlake(1, 1);
    }

    @Override
    public Serializable generate(SharedSessionContractImplementor sharedSessionContractImplementor, Object o) throws HibernateException {
        return snowFlake.nextId();
    }
}
```

```	
import jakarta.persistence.Id;
/**
* 主键
*/
@Id
@GenericGenerator(name = "yu_id", strategy = "com.xxx.common.jpa.xxx.YuIdGenerator")
@GeneratedValue(generator = "yu_id")
private Long id;
```

**Comment by Ahoo-Wang** [comment]
参考这里的代码：

https://github.com/Ahoo-Wang/CosId/blob/main/cosid-axon/src/main/java/me/ahoo/cosid/axon/CosIdIdentifierFactory.java#L33

**Comment by Ahoo-Wang** [comment]
https://github.com/apache/shardingsphere-plugin/blob/e3afa95c648edf4dcc975aa2818aa19ada2f98f8/infra/algorithm/key-generator/cosid/src/main/java/org/apache/shardingsphere/infra/algorithm/keygen/cosid/CosIdKeyGenerateAlgorithm.java#L39
