### ISSUE TITLE
spring boot 高版本运行异常

### ISSUE THREAD

**Issue by lhzsdnu** [Ahoo-Wang/CosId#64]
## Bug Report
     demo测试  spring boot 2.6.6 运行异常 ，spring boot 2.5.12 运行正常
     部分异常日志：
     1、description = 'Spring Boot [2.6.6] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [2.4.x, 2.5.x] .
      2、If you want to disable this check, just set the property [spring.cloud.compatibility-verifier.enabled=false]']]

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/Ahoo-Wang/CosId/issues).
- Read documentation: [CosId Doc](https://cosid.ahoo.me/).

Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Reason analyze (If you can)
猜测：me.ahoo.cosid:cosid-spring-boot-starter 引用 org.springframework.cloud:spring-cloud-commons 导致的版本不兼容

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/issues/8
