### ISSUE TITLE
group 可以支持自定义吗? 现在都是枚举写死了

### ISSUE THREAD

**Issue by firmianaQ** [Ahoo-Wang/CosId#649]
[**Is your feature request related to a problem? Please describe.**
号段id 分组设置可以支持自定义吗? 现在都是枚举写死了

(https://cosid.ahoo.me/guide/specific-id.html#group-year-month-day-biz)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.]

**Comment by Ahoo-Wang** [comment]
可以通过实现 `GroupBySupplier` 自行扩展。

https://github.com/Ahoo-Wang/CosId/blob/main/cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/GroupBySupplier.java#L18
