### ISSUE TITLE
针对实例由于非优雅关闭导致的机器号未被回收，建议加入心跳机制

### ISSUE THREAD

**Issue by RocherKong** [Ahoo-Wang/CosId#69]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/10215178/166637179-4eabe923-4535-4e9d-8c6f-870a08f6f31d.png)

**Describe the solution you'd like**
机器位=3多的话，最多8个实例，机器号范围：0～7. 针对实例由于非优雅关闭导致的机器号未被回收，建议加入心跳机制

**Comment by Ahoo-Wang** [comment]
![Machine-Id-Safe-Guard](https://user-images.githubusercontent.com/4384159/167164771-0c3b08b4-6d83-48d4-9dcf-88574400f7dc.png)

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CosId/tree/guard-machine-id
