### ISSUE TITLE
Add `cosid-proxy` to reduce the strong dependence of ID consumers on the distributor.

### ISSUE THREAD

**Issue by Ahoo-Wang** [Ahoo-Wang/CosId#77]
<p align="center">
<img src="https://user-images.githubusercontent.com/4384159/167278478-58479ace-d894-4488-b41e-8d82147821ce.png" alt="CosId-Proxy"/>
</p>

## SnowflakeId

`MachineIdDistributorProxy`(Client) --*http*--> `cosid-proxy`(Server/Broker)

## SegmentId

`IdSegmentDistributorProxy`(Client) --*http*--> `cosid-proxy`(Server/Broker)

**Comment by RocherKong** [comment]
扩展性很强啊
